# Numpy

Python es un lenguaje de programación muy versátil y al mismo tiempo simple en cuanto a sintaxis. Sobre la base de este lenguaje se ha creado una variedad muy grande de aplicaciones que permiten efectuar de forma simple muchas operaciones que requerirían una gran cantidad de código.

`numpy` es el paquete específico de programación científica desarrollado bajo Python, pero con estructuras en C, lo que le confiere velocidad de ejecución.

Las ventajas de `numpy` son, fundamentalmente, dos:

1. Es mucho más rápido que el núcleo de Python puesto que está precompilado en C.
2. Es vectorizable en el sentido de que podemos tratar a un grupo de datos con la facilidad de una variable, lo que permite desarrollar programas compactos y eficientes.

Para usar el paquete `numpy` debemos de importarlo. Lo hacemos con el alias `np`.

La herramienta fundamental de `numpy` son los `ndarrays`, a los que nos refereriremos como arrays. 

Veamos algunos ejemplos de cómo trabajan los arrays, en comparación con las listas de Python:

In [1]:
import numpy as np
a1=[1,2,3]  # lista
a2=[4,5,6]  # lista
b1=np.array([1,2,3])  # array de numpy
b2=np.array([4,5,6])  # array de numpy

In [2]:
a1+a2  # Sumamos dos listas

[1, 2, 3, 4, 5, 6]

In [3]:
b1+b2  # Sumamos dos arrays

array([5, 7, 9])

In [4]:
b1**2  # Un array elevado al cuadrado

array([1, 4, 9])

También es posible aplicar funciones a un array haciendo que la función se aplique a cada elemento:

In [5]:
print(np.sqrt(b1))  
print(np.exp(b2))

[ 1.          1.41421356  1.73205081]
[  54.59815003  148.4131591   403.42879349]


Vemos que el comportamiento de una lista de Python y de un array de numpy es diferente. Se trata de objetos diferentes y por eso hay que incluir en la definición del array el alias del paquete, `np` en este caso.

Las listas de Python se consideran como conjunto ordenado de objetos y por tanto al sumar dos listas se añaden. Sin embargo, los arrays son estructuras más próximas a los conceptos matemáticos de vectores y matrices.

## Creación de arrays

Un array es equivalente en forma a las listas de Python pero, a diferencia de estas, solo puede contener un tipo de datos. 
Pueden tener dimensiones, denominadas `axes` y definidas por su rango, `rank`.

Se crea con la orden `np.array(lista,dtype=tipo)`, donde `lista` es una lista, con o sin múltiples sublistas, y `tipo` indica el tipo de elementos que lo componen: `int`, `float`,  `complex`. Por defecto es `float`.

Si hay mezcla de tipos, se pasa todos los elementos al tipo superior. Con el argumento `dtype` especificamos el tipo.

In [6]:
a1=np.array([1,2,3])
a2=np.array([1.,2,3])
a3=np.array([1.,2,3],dtype=complex)

Se puede crear un array con ceros, unos o con números aleatorios: `np.zeros((shape))`, `np.ones((shape))`, `np.empty((shape))`, donde `shape` es la forma que se le quiera dar: 2x3, 4x5, ...

Se puede crear un array nuevo a partir de la forma de otro con `np.empty_like`, `np.zeros_like`, `np.ones_like`. Hereda el tipo a no ser que usemos el argumento `dtype`.

In [7]:
a= np.array([1,2,3,4])  # A partir de la lista
b= np.zeros((3,2))  # 3 filas y  2 columnas, con ceros 
c= np.ones((2,2)) # 2 filas y 2 columnas con unos
# 2 filas y 3 columnas con valores arbitrarios
d= np.empty((2,3))  
e= np.zeros_like(d,dtype=int)

In [8]:
print(c)

[[ 1.  1.]
 [ 1.  1.]]


In [9]:
print(e)

[[0 0 0]
 [0 0 0]]


La definición de cada elemento es `b[i,j]`, a diferencia de las listas donde es `b[i][j]`.

Tiene los siguientes atributos: `ndim, shape, size, dtype, itemsize, data`.

In [10]:
print(a.ndim)
print(b.shape)
print(c.size)
print(d.dtype)
print(e.itemsize)
print(a.data)

1
(3, 2)
4
float64
8


## Inicialización de un array

Con `np.arange(ini,fin,paso)` y con `np.linspace(ini,fin,num)`. Este último crea real.

A partir de una función con `np.fromfunction(fun,dim)`.

Utiliza los tipos `np.nan` y `np.inf`.

In [11]:
a= np.arange(2,8,2)
print(a)
b= np.linspace(2,8,4)
print(b)
def f(x,y):
    return x**2+y**2
c=np.fromfunction(f,(2,3))
print(c)

[2 4 6]
[ 2.  4.  6.  8.]
[[ 0.  1.  4.]
 [ 1.  2.  5.]]


## Cambiando la forma de un array

* `.reshape(dim)` genera una vista del array con la forma cambiada. El índice -1 sirve para indicar que rellene condicionado al otro índice.
* `.transpose()` o simplemente `.T` genera una vista con el transpuesto. En el caso unidimensional genera el mismo.
* `.ravel()` genera una vista plana del array.
* `.flatten()` genera una copia plana del array 

In [12]:
a= np.arange(10)
b= a.reshape(2,5)
c= a.flatten()
d= a.ravel()
print('a=',a)
print('b=',b)
a[0]=10
print('a=',a)
print('b=',b)
print('b traspuesto=',b.T)
print('c=',c)
print('d=',d)

a= [0 1 2 3 4 5 6 7 8 9]
b= [[0 1 2 3 4]
 [5 6 7 8 9]]
a= [10  1  2  3  4  5  6  7  8  9]
b= [[10  1  2  3  4]
 [ 5  6  7  8  9]]
b traspuesto= [[10  5]
 [ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]]
c= [0 1 2 3 4 5 6 7 8 9]
d= [10  1  2  3  4  5  6  7  8  9]


## Seleccionando trozos de array

In [13]:
print(b[:,1]) # La segunda columna
print(b[1]) # Segunda fila

[1 6]
[5 6 7 8 9]


## Lectura de ficheros

La lectura de un fichero de números es inmediata con numpy:

In [14]:
import numpy as np
lectura=np.genfromtxt('kk2.txt',delimiter=',')

In [15]:
print(type(lectura), lectura.size,lectura.shape)
print(lectura[1])

<class 'numpy.ndarray'> 3000 (1000, 3)
[ 2.  4.  8.]


Numpy lee el fichero y genera un array.

Para escribir y leer un array de `numpy` a un fichero en forma binaria (e independiente de la plataforma) se usan los métodos `np.save('fichero.npy', array)` y `np.load('fichero.npy')`. 
Es también posible escribir una serie de arrays y luego leerlos con la misma estructura.

In [16]:
np.save('kk.npy',b)
bleido=np.load('kk.npy')
print(bleido)

[[10  1  2  3  4]
 [ 5  6  7  8  9]]
